export const ACH_CHAR = {
  first_message:       'sherlock',
  chatty:              'sherlock',
  verbose:             'sherlock',
  daily_hero:          'sherlock',
  daily_dedicated:     'sherlock',
  mission_starter:     'el-profesor',
  mission_veteran:     'el-profesor',
  mission_elite:       'el-profesor',
  story_first:         'el-profesor',
  story_5:             'el-profesor',
  interrogation_first: 'walter-white',
  interrogation_5:     'walter-white',
  philosopher:         'gandalf',
  deep_thinker:        'gandalf',
  streak_3:            'gandalf',
  streak_7:            'gandalf',
  streak_30:           'gandalf',
  guess_good:          'gollum',
  guess_master:        'gollum',
  guess_first:         'gollum',
  guess_5:             'gollum',
  swipe_first:         'tony-stark',
  swipe_10:            'tony-stark',
  este_o_ese_first:    'tony-stark',
  confesionario_first: 'darth-vader',
  polyglot:            'jack-sparrow',
  universe_explorer:   'jack-sparrow',
  parecido_first:      'john-wick',
  all_modes:           'frodo',
  custom_char_created: 'tyrion',
}

export const MODES = [
  { label: 'Chat',           eyebrow: 'Con personaje',         route: '/chat',          color: '#4A9B7B', tag: 'Sin límite',       image: '/images/ragnarchat1a1.webp',               completionKey: null            },
  { label: 'Misión',         eyebrow: 'Historia interactiva',  route: '/mission',       color: '#D4576B', tag: '~10 min',          image: '/images/modomision.jfif',                  completionKey: 'story'         },
  { label: 'Interrogatorio', eyebrow: 'Detección de mentiras', route: '/interrogation', color: '#6D4AFF', tag: '~8 min',           image: '/images/interrogatoriojpg.jpg',            completionKey: 'interrogation' },
  { label: 'Dilemas',        eyebrow: 'Filosófico',            route: '/dilema',        color: '#C9954A', tag: '~5 min',           characterId: 'gandalf',                            completionKey: 'dilema'        },
  { label: 'Adivinar',       eyebrow: 'Trivia con puntaje',    route: '/guess',         color: '#9B4A7B', tag: '~3 min',           image: '/images/adivinaelpersonaje.webp',          completionKey: 'guess'         },
  { label: 'Swipe',          eyebrow: 'Respuesta rápida',      route: '/swipe',         color: '#4A7B9B', tag: '~2 min',           image: '/images/wolverineSwipe.jpg',               completionKey: 'swipe'         },
  { label: 'Última Cena',    eyebrow: 'Debate grupal',         route: '/ultima-cena',   color: '#8B4A2A', tag: '~15 min',          image: '/images/ultimacena2.jfif',                 completionKey: null            },
  { label: 'Duo',            eyebrow: '2 personajes',          route: '/duo',           color: '#7B9B4A', tag: 'Sin límite',       image: '/images/ipmanstevenseagal.webp',           completionKey: null            },
  { label: 'Parecido',       eyebrow: 'Quiz visual',           route: '/parecido',      color: '#9475F0', tag: '~5 min',           image: '/images/aquientepareces.jfif',             completionKey: 'parecido'      },
  { label: 'Salas',          eyebrow: 'Multijugador',          route: '/salas',         color: '#C9954A', tag: 'En vivo',          image: '/images/jaxtellersupermanchatenvivo.webp', completionKey: null            },
  { label: 'Comunidad',      eyebrow: 'Personajes de fans',    route: '/comunidad',     color: '#81c784', tag: 'Creados por fans', image: '/images/ninja.png',                        completionKey: null            },
]
